name: MultiBranchRepLearning
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - pip
  - pip:
      # PyTorch to be installed manually due to CUDA version handling
      # See installation note below
      # pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113